env: "local" # environment local/dev/prod
token_ttl: 12h  # lifetime of auth token
storage: # file or database mode switcher
  file_storage: # you only need one for each mode, basically a file, if you specify 2, the file will be used.
    file_path: "./storage/in_file_storage.json"
  database: # if use db, delete file_storage part
    uri: "postgresql://admin:secret@localhost:5432/mydatabase"
grpc:
  port: 8080
  timeout: 10h